version: '3'

services:
  app:
    build: ./
    container_name: explorer-legacy-app-dev-container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./explorers_legacy:/app/

  db:
    image: postgres:15
    container_name: postgres-db-dev-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=explorers_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5555:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: